
package de.css_lims.dkmsroboterrueckmeldung;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "DkmsRoboterRueckmeldung", targetNamespace = "http://www.css-lims.de/DkmsRoboterRueckmeldung/",
                  wsdlLocation =
                  "http://localhost:7101/WebService-DkmsRoboterRueckmeldung-context-root/DkmsRoboterRueckmeldung?WSDL#%7Bhttp%3A%2F%2Fwww.css-lims.de%2FDkmsRoboterRueckmeldung%2F%7DDkmsRoboterRueckmeldung")
public class DkmsRoboterRueckmeldung_Service extends Service {

    private final static URL DKMSROBOTERRUECKMELDUNG_WSDL_LOCATION;
    private final static WebServiceException DKMSROBOTERRUECKMELDUNG_EXCEPTION;
    private final static QName DKMSROBOTERRUECKMELDUNG_QNAME =
        new QName("http://www.css-lims.de/DkmsRoboterRueckmeldung/", "DkmsRoboterRueckmeldung");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url =
                new URL("http://localhost:7101/WebService-DkmsRoboterRueckmeldung-context-root/DkmsRoboterRueckmeldung?WSDL#%7Bhttp%3A%2F%2Fwww.css-lims.de%2FDkmsRoboterRueckmeldung%2F%7DDkmsRoboterRueckmeldung");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DKMSROBOTERRUECKMELDUNG_WSDL_LOCATION = url;
        DKMSROBOTERRUECKMELDUNG_EXCEPTION = e;
    }

    public DkmsRoboterRueckmeldung_Service() {
        super(__getWsdlLocation(), DKMSROBOTERRUECKMELDUNG_QNAME);
    }

    public DkmsRoboterRueckmeldung_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), DKMSROBOTERRUECKMELDUNG_QNAME, features);
    }

    public DkmsRoboterRueckmeldung_Service(URL wsdlLocation) {
        super(wsdlLocation, DKMSROBOTERRUECKMELDUNG_QNAME);
    }

    public DkmsRoboterRueckmeldung_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DKMSROBOTERRUECKMELDUNG_QNAME, features);
    }

    public DkmsRoboterRueckmeldung_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DkmsRoboterRueckmeldung_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns DkmsRoboterRueckmeldung
     */
    @WebEndpoint(name = "DkmsRoboterRueckmeldung")
    public DkmsRoboterRueckmeldung getDkmsRoboterRueckmeldung() {
        return super.getPort(new QName("http://www.css-lims.de/DkmsRoboterRueckmeldung/", "DkmsRoboterRueckmeldung"),
                             DkmsRoboterRueckmeldung.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DkmsRoboterRueckmeldung
     */
    @WebEndpoint(name = "DkmsRoboterRueckmeldung")
    public DkmsRoboterRueckmeldung getDkmsRoboterRueckmeldung(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.css-lims.de/DkmsRoboterRueckmeldung/", "DkmsRoboterRueckmeldung"),
                             DkmsRoboterRueckmeldung.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DKMSROBOTERRUECKMELDUNG_EXCEPTION != null) {
            throw DKMSROBOTERRUECKMELDUNG_EXCEPTION;
        }
        return DKMSROBOTERRUECKMELDUNG_WSDL_LOCATION;
    }

}
