
package de.css_lims.dkmsroboterrueckmeldung;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebService(name = "DkmsRoboterRueckmeldung", targetNamespace = "http://www.css-lims.de/DkmsRoboterRueckmeldung/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ ObjectFactory.class })
public interface DkmsRoboterRueckmeldung {


    /**
     *
     * @param rueckmeldungRequest
     * @return
     *     returns de.css_lims.dkmsroboterrueckmeldung.RueckmeldeungResponse
     */
    @WebMethod(operationName = "DkmsRoboterRueckmeldung",
               action = "http://www.css-lims.de/DkmsRoboterRueckmeldung/DkmsRoboterRueckmeldung")
    @WebResult(name = "RueckmeldeungResponse", targetNamespace = "http://www.css-lims.de/DkmsRoboterRueckmeldung/",
               partName = "RueckmeldeungResponse")
    public RueckmeldeungResponse dkmsRoboterRueckmeldung(@WebParam(name = "RueckmeldungRequest",
                                                                   targetNamespace =
                                                                   "http://www.css-lims.de/DkmsRoboterRueckmeldung/",
                                                                   partName = "RueckmeldungRequest")
                                                         RueckmeldungRequest rueckmeldungRequest);

}
