package de.css_lims.dkmsroboterrueckmeldung;

import static de.css_lims.dkmsroboterrueckmeldung.RueckmeldungRequest.DynamischerTeil;
import static de.css_lims.dkmsroboterrueckmeldung.RueckmeldungRequest.DynamischerTeil.DynamischerTyp;
import static de.css_lims.dkmsroboterrueckmeldung.RueckmeldungRequest.DynamischerTeil.DynamischerTyp.DynamischesObjekt;
import static de.css_lims.dkmsroboterrueckmeldung.RueckmeldungRequest.DynamischerTeil.DynamischerTyp.DynamischesObjekt.WertObjekt;
import de.css_lims.dkmsroboterrueckmeldung.de.css_lims.dkmsroboterrueckmeldung.types.MaterialKeys;
import de.css_lims.dkmsroboterrueckmeldung.de.css_lims.dkmsroboterrueckmeldung.types.TargetKeys;

import java.math.BigInteger;

import java.util.EnumMap;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.UUID;

import javax.xml.datatype.DatatypeConfigurationException;
import javax.xml.datatype.DatatypeFactory;
import javax.xml.datatype.XMLGregorianCalendar;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 12c Development Build 12.2.1.1.0.2047
public class DkmsRoboterRueckmeldungClient {

    private static List<DynamischerTyp> dTypList;
    private static DynamischerTeil dTeil;
    private static DynamischesObjekt dObjekt;

    public static void main(String[] args) {
        DkmsRoboterRueckmeldung_Service dkmsRoboterRueckmeldung_Service = new DkmsRoboterRueckmeldung_Service();
        DkmsRoboterRueckmeldung dkmsRoboterRueckmeldung = dkmsRoboterRueckmeldung_Service.getDkmsRoboterRueckmeldung();
        // Add your code to call the desired methods.

        RueckmeldungRequest rueckmeldungRequest = initializeRequest(1);
        createDynamischesObject(dTypList.get(0), "1");
        List<WertObjekt> wObjektList = dObjekt.getWertObjekt();
      
        EnumMap<MaterialKeys, String> sourceMap = new EnumMap<>(MaterialKeys.class);
        sourceMap.put(MaterialKeys.ID, "Mat-Id");
        sourceMap.put(MaterialKeys.TYPE, "MATERIAL");
        sourceMap.put(MaterialKeys.NAME, "HLA-A");
        sourceMap.put(MaterialKeys.CONTAINER, "384");

        createObjektList(wObjektList, sourceMap);
        
        RueckmeldungResponse rueckmeldungResponse =
            dkmsRoboterRueckmeldung.dkmsRoboterRueckmeldung(rueckmeldungRequest);
        System.err.println(rueckmeldungResponse.getStatus());

    } // end main

    private static void createDynamischesObject(DynamischerTyp dTyp, String position) {
        /*
         * every dTyp has a DynamischesObjektList
         */
   
        List<DynamischesObjekt> dObjektList = dTyp.getDynamischesObjekt();
        /*
        * create the DynamischesObjekt
        */
         dObjekt = new DynamischesObjekt();
        /*
         * and set the position
         */
        dObjekt.setPosition(new BigInteger(position));
        dObjektList.add(dObjekt);
        /*
         * and get and fill the  List<WertObjekt> wObjektList
         */
        List<WertObjekt> wObjektList = dObjekt.getWertObjekt();


    }

    private static void createObjektList(List<WertObjekt> wObjektList, EnumMap<? extends Enum, String> werteMap) {
        // for (Object o :  )
        Iterator<?> enumKeySet = werteMap.keySet().iterator();
        while (enumKeySet.hasNext()) {

            Object key = enumKeySet.next();
            // System.out.println(key.getClass());
            if (key instanceof MaterialKeys) {
                MaterialKeys temp = (MaterialKeys) key;
                WertObjekt wObjekt = new WertObjekt();
                wObjekt.setName(temp.name());
                wObjekt.setInhalt(werteMap.get(temp));
                wObjektList.add(wObjekt);
            }
            if (key instanceof TargetKeys) {
                TargetKeys temp = (TargetKeys) key;
                WertObjekt wObjekt = new WertObjekt();
                wObjekt.setName(temp.name());
                wObjekt.setInhalt(werteMap.get(temp));
                wObjektList.add(wObjekt);

            }
        }

    }

    private static RueckmeldungRequest initializeRequest(int typ) {
        RueckmeldungRequest rueckmeldungRequest = new RueckmeldungRequest();

        /*
         * Build the static content of the Request
         */
        GregorianCalendar gcal = new GregorianCalendar();
        XMLGregorianCalendar xgcal = null;
        try {
            xgcal = DatatypeFactory.newInstance().newXMLGregorianCalendar(gcal);
        } catch (DatatypeConfigurationException e) {
            System.err.println(e.getStackTrace());
        }
        rueckmeldungRequest.setZeitstempel(xgcal);
        rueckmeldungRequest.setRackId("Test3");
        rueckmeldungRequest.setRoboterId("MSM1");
        rueckmeldungRequest.setUserBedienerId("boehm");
        rueckmeldungRequest.setProgrammId("001");
        rueckmeldungRequest.setHinweisText("MSM1 ist defekt");
        /*
         * optional userKontrolleurId
         */
        rueckmeldungRequest.setUserKontrolleurId("boehm");


        /*
         * realize a unique requestId from diverse robots
         */
        String uniqueID = UUID.randomUUID().toString();
        rueckmeldungRequest.setRequestId(uniqueID);

        /*
         *  Questions:
         *  What can be transported by using requestTyp ?
         *  0 = Test & Validate
         *  1 = Track
         */

        rueckmeldungRequest.setRequestTyp(new BigInteger(String.valueOf(typ)));
        /*
         * set dynamischen Teil - there is only ONE in each XML request.
         */
        dTeil = new DynamischerTeil();
        rueckmeldungRequest.setDynamischerTeil(dTeil);

        /*
         * dTeil has ONE List of dTyps, so get and fill it
         */
        dTypList = rueckmeldungRequest.getDynamischerTeil().getDynamischerTyp();

        /*
         * create ALL DynamischerTyp "MATERIALS", SOURCE_POS and "TARGET_POS" and add to
         * dTypList
         */

        DynamischerTyp dTyp = new DynamischerTyp();
        dTyp.setName("MATERIALS");
        dTypList.add(dTyp);

        //                dTyp = new DynamischerTyp();
        //                dTyp.setName("SOURCE_POS");
        //                dTypList.add(dTyp);
        //
        //                dTyp = new DynamischerTyp();
        //                dTyp.setName("TARGET_POS");
        //                dTypList.add(dTyp);


        return rueckmeldungRequest;
    }
}
